ruby/.rubocop.yml

@primiti  Can you review? I tested these changes interactively like you suggested.

disable "Use match? instead of =~ when MatchData is not used." and "Use @ivar.positive? instead of @ivar > 0."

---

ruby/.rubocop.yml

Rubcop complains about variables like `found_utf_16` or `sha256`.  This isn't in our style guide.

disable Naming/VariableNumber cop

---

ruby/.rubocop.yml

Our code has a mix of styles, depending on whether the developer thought fixed spacing or tabular would pay off. (Often < 3 looks find with fixed, but > 7 definitely tabular.)

disable Layout/AlignHash

---

ruby/README.md

Sorry for the whitespace cleanup spam - editor automatically fixed those
This adds enforcing namespace definitions for classes to our style guide

add class namespacing: add Namespace Definitions to ruby style guide

---

ruby/.rubocop.yml

* Removes Cops that were removed/not being targeted
* Updates `TargetRubyVersion`

ruby-2.6: update rubocop config for ruby 2.6.1

---

.hound.yml

http://help.houndci.com/en/articles/2489940-linter-versioning
http://help.houndci.com/en/articles/2461415-supported-linters
Bumping the rubocop version for hound

hound rubocop version: update hound preferred rubocop version

---

javascript/.eslintrc.json

This PR turns on "always" for enforcing a space after async arrow function.

ESLint Async Error Function Spacing

---

ruby/.rubocop.yml
ruby/README.md

Hound has had the rule:
"Style/BracesAroundHashParameters: Redundant curly braces around a hash parameter."
https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/BracesAroundHashParameters
which I feel like it obfuscates the fact that we need to pass a hash to a method. It's more explicit to pass it as a hash when you're using the hash directly in the called method.
More importantly ruby is actually changing how it deals with hashes in 3.0 in a way that will likely cause this rule to change anyway:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

Allow curly braces when sending hashes as arguments

---

ruby/.rubocop.yml
ruby/README.md

* Disable `Style/BracesAroundHashParameters` in order to prep for Ruby 3 changes.
* Add examples to README
* `Do not use a hash literal to destructure keyword args.`
* `Use '{}' when passing a hash as an argument for a method that also includes keyword args.`
* Remove examples from README
* `Use '{}' when passing a hash as an argument, but not for keyword args.`

Remove curly brace requirement for ruby 3

---

ruby/.rubocop.yml
ruby/README.md

See [this slack thread](https://invoca.slack.com/archives/C8P8R355G/p1587677133001600) for more context.
Prefer using templated string format to make it clear what you're formatting (extra beneficial for the use case where there are multiple values you are templating)

format enforce templated string formatting

---

.github/CODEOWNERS

@alecjacobs5401 @peterwilson @nburwell 
I've enabled the `github` setting that requires at least one approval for any PR to be merged in this repo. Given that, I don't think any of us need to be "CODEOWNERS". We can still watch the repo if we like.

no-jira: drop CODEOWNERS

---

ruby/.rubocop.yml

This parameter isn't valid, I suspect something changed with the bump to rubocop 0.91.0.  The cop is enabled by default, so removing the offending parameter should be a noop.
@alecjacobs5401 and @ColinDKelley: git says you were both recently in the area, so I've tagged you for review.
```
Warning: Layout/HeredocIndentation does not support EnforcedStyle parameter.
Supported parameters are:
- Enabled
```

No JIRA: Remove invalid Layout/HeredocIndentation cop config

---

scss/.scss-lint.yml

Our `web` repo has a lot of legacy code with dynamically generated `snake_case` classnames. Often times, during a simple code update, Hound will complain that these classes are not valid, causing us to either find/replace/refactor a large amount of code (which can be risky, or at the very least increase the scope of the case), or put ignore statements around the CSS rules.
Brought these concerns to the UI guild meeting and we decided it was fine to simply update the linter rules to remove `hyphenated_BEM` enforcement. 
This Jira is to disable that rule.

no-jira: disable hyphenated_BEM css rule

---

ruby/.rubocop.yml

As a passion project I am trying to bump the rubocop version in the web repo.   When it is bumped it complains about cops that are not mentioned.  This change fixes it so that it will not complain.   We may need to come back and tune things later.

Enable new cops by default, bump target ruby version to match web

---

ruby/.rubocop.yml

- Move the LineLength cop configuration to the appropriate namespace
[Jira Story](https://invoca.atlassian.net/browse/STORY-14443)

STORY-14443 - Address breaking change introduced by rubocop in 0.78.0 on  2019-12-18

---

ruby/.rubocop.yml

This PR disables the `RSpec/NotToNot` cop. By default that's enabled, and it complains about our common usage
```
expect(r).to_not receive(:puts)
```

non-production: disable RSpec/NotToNot

---

ruby/.rubocop.yml

Seeing failed Hound errors.
https://github.com/Invoca/web/pull/21187 Hound — ./ruby/.rubocop.yml format is invalid 
Proof that it works fine with Hound https://github.com/Invoca/web/pull/21188

Fix cop style

---

ruby/.rubocop.yml

This reverts commit 23cde1ed4af737dd704e2193bbab5e3b2fefa062 and the `:` fix.

Revert "non-production: disable RSpec/NotToNot"

---

ruby/.rubocop.yml

I'm working to set up the new rubocop to automatically correct ruby 2-7 keyword arg deprecation warnings. However this exclude is preventing the rubocop from correcting issues in config.rb.
This seems strange to exclude ruby files in the config directory from rubocop.

NON-PROD remove config from exclude folder

---

ruby/.rubocop.yml

I TDD'd with a file that had both of these offenses:
```ruby
if Rails.env == :'test'
puts 'test'
end
```
and proved that they went away with these changes.

non-production/disable EnvironmentComparison and QuotedSymbols
